spring.application.name=crypto-price-tracker-api

# H2 ???? DB ??
spring.datasource.url=jdbc:h2:mem:cryptodb;MODE=MySQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.data-locations=classpath:data.sql

# H2 ?? (???, http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# schema.sql ?? ??
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:static/schema.sql

# ?? ??
server.port=8080
