
CREATE TABLE coin (

    id BIGINT AUTO_INCREMENT PRIMARY KEY, -- 코인 id
    symbol VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    api_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE price_history (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    coin_id    BIGINT NOT NULL,
    price_usd  DECIMAL(20, 8) NOT NULL,
    fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (coin_id) REFERENCES coin(id)
);
